version: "2"
services:
  node:
    container_name: node
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    build: ./mongo
    env_file: .env
    volumes:
      - ./mongo/data:/data/db
    ports:
      - "27017:27017"